version: "3"
services:
  userservice:
    image: loriszn/server-setup:user_service
    container_name: user-service
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./database/userdb

  compilerservice:
    image: loriszn/server-setup:compiler_service
    container_name: compiler-service
    ports:
      - '8083:8083'

  leaderboardservice:
    image: loriszn/server-setup:leaderboard_service
    container_name: leaderboard-service
    ports:
      - '8087:8087'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./database/leaderboarddb

  exerciseservice:
    image: loriszn/server-setup:exercise_service
    container_name: exercise-service
    ports:
      - '9090:9090'
    volumes:
      - assignments:/usr/src/app/assets/assignments

  frontend:
    image: loriszn/server-setup:frontend
    container_name: frontend
    ports:
      - '4200:80'

volumes:
  assignments:
    external: true



